#!/bin/bash

# Stop on errors
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

# create python virtual env
python3 -m venv env
source env/bin/activate

# install backend
pip install -r requirements.txt

# install frontend
npm run postinstall