export const prot_type = {
  0: "idmp",
  1: "udp",
  2: "tcp",
};

export const service_type = {
  9: "http",
  11: "private",
  0: "domain_u",
  1: "smtp",
  10: "ftp_data",
  3: "eco_i",
  13: "other",
  7: "ecr_i",
  6: "telnet",
  2: "finger",
  61: "ftp",
  5: "auth",
  8: "Z39_50",
  4: "courier",
  12: "uucp",
  15: "time",
  46: "bgp",
  18: "whois",
  19: "imap4",
  25: "uucp_path",
  41: "iso_tsap",
  23: "ctf",
  44: "urp_i",
  42: "nnsp",
  29: "supdup",
  40: "http_443",
  14: "csnet_ns",
  22: "efs",
  53: "domain",
  34: "gopher",
  28: "daytime",
  36: "vmnet",
  48: "discard",
  51: "hostnames",
  16: "name",
  54: "klogin",
  49: "exec",
  37: "ldap",
  38: "mtp",
  55: "systat",
  20: "netbios_dgm",
  43: "link",
  31: "login",
  24: "netstat",
  45: "netbios_ns",
  35: "netbios_ssn",
  26: "sunrpc",
  17: "kshell",
  50: "echo",
  47: "nntp",
  57: "ssh",
  52: "pop_3",
  33: "sql_net",
  32: "IRC",
  39: "ntp_u",
  21: "X11",
  27: "rje",
  58: "remote_job",
  56: "pop_2",
  30: "printer",
  59: "shell",
  60: "urh_i",
  64: "red_i",
  62: "pm_dump",
  63: "tim_i",
  65: "http_8001",
};

export const flag_types = {
  0: "SF",
  4: "S0",
  2: "REJ",
  7: "RSTR",
  6: "RSTO",
  10: "S1",
  1: "SH",
  3: "RSTOS0",
  8: "S2",
  5: "S3",
  9: "OTH",
};

export interface nid_data {
  duration: Number;
  protocol_type: Number;
  service: Number;
  flag: Number;
  src_bytes: Number;
  dst_bytes: Number;
  land: Number;
  wrong_fragment: Number;
  urgent: Number;
  hot: Number;
  num_failed_logins: Number;
  logged_in: Number;
  num_compromised: Number;
  root_shell: Number;
  su_attempted: Number;
  num_root: Number;
  num_file_creations: Number;
  num_shells: Number;
  num_access_files: Number;
  num_outbound_cmds: Number;
  is_host_login: Number;
  is_guest_login: Number;
  count: Number;
  srv_count: Number;
  serror_rate: Number;
  srv_serror_rate: Number;
  rerror_rate: Number;
  srv_rerror_rate: Number;
  same_srv_rate: Number;
  diff_srv_rate: Number;
  srv_diff_host_rate: Number;
  dst_host_count: Number;
  dst_host_srv_count: Number;
  dst_host_same_srv_rate: Number;
  dst_host_diff_srv_rate: Number;
  dst_host_same_src_port_rate: Number;
  dst_host_srv_diff_host_rate: Number;
  dst_host_serror_rate: Number;
  dst_host_srv_serror_rate: Number;
  dst_host_rerror_rate: Number;
  dst_host_srv_rerror_rate: Number;
  pred: String;
}
